name: Code checks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ matrix.extensions }}
          ini-values: max_input_vars=5000
          tools: cs2pr, phpcs, php-cs-fixer
          coverage: none

      - name: Checkout ilias-plugin-ci repository
        run: git clone https://github.com/oc-group/ilias-plugin-ci.git ilias-plugin-ci

      - name: Run PHP CS Fixer
        run: php-cs-fixer fix --config=ilias-plugin-ci/.php-cs-fixer.php --using-cache=no --dry-run --diff

      - name: Run PHP CodeSniffer
        run: phpcs --standard=ilias-plugin-ci/phpcs.xml --extensions=php -s --report-width=132

      - name: Mark cancelled jobs as failed.
        if: ${{ cancelled() }}
        run: exit 1
